### ISSUE TITLE
Hosted method still dosen't work(linux)

### ISSUE THREAD

**Issue by Sohail-XD** [kholmogorov27/chevron#14]
> chevron@2.2.0 register_linux
> node backend/register.cjs linux

Using default mode: systemd
Registering the service
Installing service on /etc/systemd/system/chevron.service
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/etc/systemd/system/chevron.service'
Emitted 'error' event on daemon instance at:
    at init.<anonymous> (/usr/lib/node_modules/node-linux/lib/daemon.js:491:42)
    at init.emit (node:events:513:28)
    at /usr/lib/node_modules/node-linux/lib/systemd.js:199:36
    at node:fs:2171:7
    at FSReqCallback.oncomplete (node:fs:192:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/etc/systemd/system/chevron.service'
}

**Comment by Sohail-XD** [comment]
I did run it with sudo

**Comment by noir-Z** [comment]
I have the same issue, is there anything I can do to help?

**Comment by kholmogorov27** [comment]
I don't know yet what creates this error, it could be a problem with `node-linux` library that chivron uses. One way or another, you can compile the application yourself.

- Clone this repository
- [Build](https://github.com/kholmogorov27/chevron#build)
- Run 
```bash
npm run compile
```

it will create an executable file which starts Chevron server. You can add this file to autorun or make it a service on your OS.
